name = "mytest"
# hashicorp/go-getter URLs, so in the future we can support fetching test plans
# from GitHub.
source_path = "file://${TESTGROUND_SRCDIR}/plans/mytest"

[defaults]
builder = "exec:go"
runner = "local:exec"

[build_strategies."docker:go"]
enabled = true
go_version = "1.13"
module_path = "github.com/ipfs/testground/plans/mytest"
exec_pkg = "."

# TODO: exec:go is not ready yet
[build_strategies."exec:go"]
enabled = true
module_path = "github.com/ipfs/testground/plans/mytest"
exec_pkg = "."

[run_strategies."local:docker"]
enabled = true

[run_strategies."local:exec"]
enabled = true

[run_strategies."cluster:swarm"]
enabled = true

[run_strategies."cluster:k8s"]
enabled = true

# seq 0
[[testcases]]
name = "first-try"
instances = { min = 16, max = 10000, default = 16 }

  [testcases.params]
